In [1]:
import pandas as pd
import numpy as np
import sklearn as sk
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder


e:\Anaconda\envs\ahmed_env\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
from sklearn.model_selection import  train_test_split

In [2]:
train_data=pd.read_csv('titanic/train.csv')

In [3]:
test_data=pd.read_csv('titanic/test.csv')

#### Fill missing Cabin cells

In [4]:

for i in range(len(train_data['Cabin'])):
    try:
        train_data.at[i,'Cabin']=train_data.at[i,'Cabin'][0]
    except:
        train_data.at[i,'Cabin']='No Cabin'

In [5]:

for i in range(len(test_data['Cabin'])):
    try:
        test_data.at[i,'Cabin']=test_data.at[i,'Cabin'][0]
    except:
        test_data.at[i,'Cabin']='No Cabin'

### Categorize tickets

In [6]:

for i in range(len(train_data['Ticket'])):
    try:
        int(train_data.at[i,'Ticket'])
        train_data.at[i,'Ticket']='normal ticket'
    except:
        train_data.at[i,'Ticket']=train_data.at[i,'Ticket'][0]

In [7]:

for i in range(len(test_data['Ticket'])):
    try:
        int(test_data.at[i,'Ticket'])
        test_data.at[i,'Ticket']='normal ticket'
    except:
        test_data.at[i,'Ticket']=test_data.at[i,'Ticket'][0]

### Obtain title, fill the age with median corresponding title and change rare titles

In [8]:
train_data['Name']=train_data['Name'].apply(lambda x: x.split(",")[1].split(".")[0])
test_data['Name']=test_data['Name'].apply(lambda x: x.split(",")[1].split(".")[0])
temp_df=train_data[['Name','Age']]
temp_df=temp_df.groupby('Name').aggregate({'Age': [np.median, np.count_nonzero]})
temp_df=pd.DataFrame({'Name':list(temp_df.index),'Age':list(temp_df.values.flatten('F'))[0:len(temp_df)],
'Count':list(temp_df.values.flatten('F'))[len(temp_df):]})
temp_df=temp_df.T
temp_df.columns = temp_df.iloc[0]
temp_df = temp_df[1:]

In [9]:

test_data=test_data.replace(np.nan,-1) #this will also modify the Embarked column
#fill missing age
for i in range(len(test_data['Name'])):
    if test_data.at[i,'Age']==-1:
        test_data.at[i,'Age']=temp_df.iloc[0][test_data.at[i,'Name']]
#replace rare titles
for i in range(len(test_data['Name'])):
    try:
        if temp_df.at['Count',test_data.at[i,'Name']]<5:
            test_data.at[i,'Name']=' Rare'
    except:
        test_data.at[i,'Name']=' Rare'

In [10]:

train_data=train_data.replace(np.nan,-1) #this will also modify the Embarked column
#fill missing age
for i in range(len(train_data['Name'])):
    if train_data.at[i,'Age']==-1:
        train_data.at[i,'Age']=temp_df.iloc[0][train_data.at[i,'Name']]
#replace rare titles
for i in range(len(train_data['Name'])):
    try:
        if temp_df.at['Count',train_data.at[i,'Name']]<5:
            train_data.at[i,'Name']=' Rare'
    except:
        train_data.at[i,'Name']=' Rare'

### Code sexes

In [11]:

train_data['Sex']=train_data['Sex'].apply(lambda x: 1 if x=='male' else 0)

test_data['Sex']=test_data['Sex'].apply(lambda x: 1 if x=='male' else 0)


### Replace misiing Embarked cells

In [12]:

train_data['Embarked']=train_data['Embarked'].apply(lambda x: "X" if x==-1 else x)

test_data['Embarked']=test_data['Embarked'].apply(lambda x: "X" if x==-1 else x)


In [13]:
train_data.to_csv('temp.csv')

In [14]:
test_data['Fare']=test_data['Fare'].apply(lambda x: 20 if x<0 else x)

### One hot encode dummy variables

In [15]:

categorical_cols = ['Name', 'Ticket', 'Cabin', 'Embarked'] 
# instantiate labelencoder object
le = LabelEncoder()
# apply le on categorical feature columns
train_data[categorical_cols] = train_data[categorical_cols].apply(lambda col: le.fit_transform(col))    
ohe = OneHotEncoder()

categorical_cols = ['Name', 'Ticket', 'Cabin', 'Embarked'] 
# instantiate labelencoder object
le = LabelEncoder()
# apply le on categorical feature columns
test_data[categorical_cols] = test_data[categorical_cols].apply(lambda col: le.fit_transform(col))    
ohe = OneHotEncoder()

In [35]:
#data_final=pd.get_dummies(data,columns=['Name', 'Ticket', 'Cabin', 'Embarked'] )


In [16]:
Xtr = train_data.iloc[:, 2:].values
Ytr =train_data.iloc[:, 1]

In [20]:
Xts=test_data.iloc[:, 1:].values

In [18]:
Xtr

array([[ 3.    ,  3.    ,  1.    , ...,  7.25  ,  7.    ,  2.    ],
       [ 1.    ,  4.    ,  0.    , ..., 71.2833,  2.    ,  0.    ],
       [ 3.    ,  2.    ,  0.    , ...,  7.925 ,  7.    ,  2.    ],
       ...,
       [ 3.    ,  2.    ,  0.    , ..., 23.45  ,  7.    ,  2.    ],
       [ 1.    ,  3.    ,  1.    , ..., 30.    ,  2.    ,  0.    ],
       [ 3.    ,  3.    ,  1.    , ...,  7.75  ,  7.    ,  1.    ]])

In [21]:
Xts

array([[ 3.    ,  3.    ,  1.    , ...,  7.8292,  7.    ,  1.    ],
       [ 3.    ,  4.    ,  0.    , ...,  7.    ,  7.    ,  2.    ],
       [ 2.    ,  3.    ,  1.    , ...,  9.6875,  7.    ,  1.    ],
       ...,
       [ 3.    ,  3.    ,  1.    , ...,  7.25  ,  7.    ,  2.    ],
       [ 3.    ,  3.    ,  1.    , ...,  8.05  ,  7.    ,  2.    ],
       [ 3.    ,  1.    ,  1.    , ..., 22.3583,  7.    ,  0.    ]])

In [146]:
#from sklearn.model_selection import  train_test_split
#Xtr,Xts,Ytr,Yts = train_test_split(X,Y,test_size=0.2,random_state=0)

In [151]:
#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#Xtr = sc.fit_transform(Xtr)
#Xts = sc.transform(Xts)

In [22]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(Xtr, Ytr)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [23]:
Yprd=np.around(classifier.predict(Xts),0)


In [ ]:
Yprd

In [25]:
result=pd.DataFrame({'PassengerId':list(test_data['PassengerId']),'Survived':Yprd})

In [27]:
result.to_csv('gender_submission.csv')

In [154]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Yts, Yprd)

array([[101,   9],
       [ 21,  48]], dtype=int64)

In [155]:
from sklearn.metrics import accuracy_score
accuracy_score(Yts, Yprd)

0.8324022346368715